# Generated by Django 3.0.6 on 2020-06-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECAs', '0003_auto_20200527_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ('-act_date',)},
        ),
        migrations.AlterField(
            model_name='activities',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ECAs.TypeActivities', verbose_name='نوع النشاط '),
        ),
    ]
