# Generated by Django 3.0.6 on 2020-10-05 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-vedio_date',)},
        ),
        migrations.AddField(
            model_name='video',
            name='vedio_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
